# Generated by Django 5.2.7 on 2025-12-03 23:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='stock_categ_name_462dc8_idx'), models.Index(fields=['is_active'], name='stock_categ_is_acti_e78ca8_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('yearly', 'Yearly Report'), ('custom', 'Custom Period'), ('valuation', 'Valuation Report'), ('turnover', 'Turnover Analysis'), ('audit', 'Audit Report'), ('low_stock', 'Low Stock Report'), ('expiry', 'Expiry Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('report_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('report_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('credit_terms', models.CharField(blank=True, help_text='Payment terms', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='stock_suppl_name_35530e_idx'), models.Index(fields=['is_active'], name='stock_suppl_is_acti_c4baa4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('max_stock_level', models.PositiveIntegerField(default=1000)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('deprecated', 'Deprecated'), ('obsolete', 'Obsolete')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stock.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stock.supplier')),
                ('valuation_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stock.valuationmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(default=1000, help_text='Maximum capacity in units')),
                ('current_utilization', models.PositiveIntegerField(default=0, help_text='Current utilization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoverAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_in_days', models.PositiveIntegerField()),
                ('average_daily_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_quantity_sold', models.PositiveIntegerField(default=0)),
                ('average_inventory', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('turnover_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('days_inventory_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_analysis', to='stock.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_analysis', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release'), ('transfer', 'Warehouse Transfer'), ('audit', 'Inventory Audit'), ('correction', 'Stock Correction')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='stock.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('beginning_quantity', models.IntegerField(default=0)),
                ('quantity_in', models.IntegerField(default=0)),
                ('quantity_out', models.IntegerField(default=0)),
                ('ending_quantity', models.IntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_status', models.CharField(max_length=20)),
                ('reorder_level', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.stockreport')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='stockreport',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('reorder', 'Reorder Level'), ('expiry_critical', 'Critical Expiry'), ('expiry_warning', 'Expiry Warning'), ('overstock', 'Overstock'), ('discrepancy', 'Audit Discrepancy')], max_length=20)),
                ('current_quantity', models.IntegerField()),
                ('threshold_value', models.IntegerField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('audit_date', models.DateField()),
                ('planned_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('discrepancy', 'Discrepancy Found')], default='planned', max_length=20)),
                ('total_items_audited', models.PositiveIntegerField(default=0)),
                ('total_discrepancies', models.PositiveIntegerField(default=0)),
                ('total_value_adjusted', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_audits', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('adjustment_type', models.CharField(choices=[('cycle_count', 'Cycle Count'), ('full_audit', 'Full Physical Audit'), ('shrinkage', 'Shrinkage'), ('damage', 'Damage'), ('theft', 'Theft'), ('miscount', 'M recount'), ('reconciliation', 'System Reconciliation')], max_length=20)),
                ('reason', models.CharField(choices=[('count_variance', 'Count Variance'), ('damage', 'Damaged Goods'), ('expiration', 'Expired Goods'), ('theft', 'Theft/Loss'), ('transfer_error', 'Transfer Error'), ('system_error', 'System Error'), ('manual_adjustment', 'Manual Adjustment')], max_length=20)),
                ('adjustment_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_increase', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_decrease', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_adjustments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_adjustments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='stock.warehouse')),
            ],
            options={
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='stock.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='stock.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='stock.stock')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.warehousetransfer')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField()),
                ('counted_quantity', models.IntegerField()),
                ('quantity_change', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('variance_reason', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.inventoryadjustment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['adjustment', 'stock'], name='stock_inven_adjustm_393c35_idx'), models.Index(fields=['quantity_change'], name='stock_inven_quantit_de064a_idx')],
                'unique_together': {('adjustment', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField()),
                ('counted_quantity', models.IntegerField()),
                ('discrepancy', models.IntegerField(default=0)),
                ('discrepancy_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.inventoryaudit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['audit', 'stock'], name='stock_audit_audit_i_49a16a_idx'), models.Index(fields=['is_corrected'], name='stock_audit_is_corr_de0655_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='stock.stockbatch')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_usages', to='stock.stocktransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'transaction'], name='stock_stock_batch_i_b2324f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='stock_wareh_code_4b9db3_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='stock_wareh_is_acti_ee1e14_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoveranalysis',
            index=models.Index(fields=['stock', 'warehouse'], name='stock_turno_stock_i_d6e4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoveranalysis',
            index=models.Index(fields=['period_start', 'period_end'], name='stock_turno_period__f7dac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turnoveranalysis',
            unique_together={('stock', 'warehouse', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['stock', 'transaction_type', 'created_at'], name='stock_stock_stock_i_5d1998_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['from_warehouse', 'created_at'], name='stock_stock_from_wa_98698d_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['to_warehouse', 'created_at'], name='stock_stock_to_ware_2bc6db_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='stock_stock_created_c38b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreportdetail',
            index=models.Index(fields=['report', 'stock'], name='stock_stock_report__71fcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreportdetail',
            index=models.Index(fields=['report', 'warehouse'], name='stock_stock_report__93bb1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockreportdetail',
            unique_together={('report', 'stock', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='stockreport',
            index=models.Index(fields=['warehouse', 'report_date'], name='stock_stock_warehou_26a29a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreport',
            index=models.Index(fields=['report_type', 'report_date'], name='stock_stock_report__e10dac_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreport',
            index=models.Index(fields=['generated_by'], name='stock_stock_generat_6d1ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['stock', 'warehouse', 'received_date'], name='stock_stock_stock_i_ccc916_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='stock_stock_expiry__7642df_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_number'], name='stock_stock_batch_n_758a08_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['is_active'], name='stock_stock_is_acti_f3dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['stock', 'warehouse'], name='stock_stock_stock_i_102593_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='stock_stock_alert_t_c80da8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['severity', 'created_at'], name='stock_stock_severit_c9a91b_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item_code'], name='stock_stock_item_co_2067bf_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['barcode'], name='stock_stock_barcode_0e4a17_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_active', 'status'], name='stock_stock_is_acti_a2a6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['category'], name='stock_stock_categor_47f6da_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['warehouse', 'status'], name='stock_inven_warehou_119c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['adjustment_date'], name='stock_inven_adjustm_a0cc06_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['adjustment_type'], name='stock_inven_adjustm_c5c81a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['status'], name='stock_inven_status_21c224_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['stock', 'warehouse'], name='stock_wareh_stock_i_bda65e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['quantity'], name='stock_wareh_quantit_310a52_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['reserved_quantity'], name='stock_wareh_reserve_4e5034_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('stock', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['transfer_number'], name='stock_wareh_transfe_e4fac9_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['status'], name='stock_wareh_status_8cb965_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['from_warehouse', 'status'], name='stock_wareh_from_wa_b768eb_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['to_warehouse', 'status'], name='stock_wareh_to_ware_45927c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferitem',
            index=models.Index(fields=['transfer', 'stock'], name='stock_trans_transfe_770bcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferitem',
            unique_together={('transfer', 'stock')},
        ),
    ]
