# Generated by Django 5.2.7 on 2026-01-25 19:44

import django.db.models.deletion
import django.utils.timezone
import upload.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_customuser_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=upload.models.get_upload_path, verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_image', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('is_audio', models.BooleanField(default=False)),
                ('is_document', models.BooleanField(default=False)),
                ('temporary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
            },
            bases=(models.Model, upload.models.ImageProcessingMixin),
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('uploadedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.uploadedfile')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
            bases=('upload.uploadedfile',),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('uploadedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.uploadedfile')),
                ('crop_to_square', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
            },
            bases=('upload.uploadedfile',),
        ),
        migrations.CreateModel(
            name='StickerFile',
            fields=[
                ('uploadedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.uploadedfile')),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
            bases=('upload.uploadedfile',),
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('uploadedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.uploadedfile')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=upload.models.get_upload_path)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
            bases=('upload.uploadedfile',),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('uploadedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload.uploadedfile')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.chatmessage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
            bases=('upload.uploadedfile',),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'uploaded_at'], name='upload_uplo_user_id_4ba6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['mime_type'], name='upload_uplo_mime_ty_a9fa64_idx'),
        ),
    ]
