# Generated by Django 5.2.7 on 2025-12-22 21:58

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_village_options_alter_village_unique_together_and_more'),
        ('fleet', '0005_alter_vehicle_brand_alter_vehicle_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('total_customers', models.PositiveIntegerField(default=0, editable=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Average rating (1-5 stars)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('expected_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('last_ai_update', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collectors', to='fleet.vehicle')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'collector'}, on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
                ('villages', models.ManyToManyField(help_text='Villages this collector is responsible for', related_name='collector_assignments', to='customers.village')),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
            },
        ),
        migrations.CreateModel(
            name='CollectorLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='collector.collector')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CollectorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previous_month_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentage_achieved', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_targets', to='collector.collector')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.village')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='collector.collector')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollector',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('total_customers', models.PositiveIntegerField(default=0, editable=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Average rating (1-5 stars)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('expected_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('last_ai_update', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicle')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Collector',
                'verbose_name_plural': 'historical Collectors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VehicleTurnCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('monthly_total', models.PositiveIntegerField(default=0, editable=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.village')),
            ],
        ),
        migrations.CreateModel(
            name='WasteCollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(default=2025)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_waste_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='collector.collector')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='fleet.vehicle')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_schedules', to='customers.village')),
            ],
        ),
        migrations.AddIndex(
            model_name='collector',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='collector_c_search__78d77c_gin'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['user', 'is_active'], name='collector_c_user_id_e16468_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['rating'], name='collector_c_rating_f51bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['efficiency_percentage'], name='collector_c_efficie_071cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorlocationhistory',
            index=models.Index(fields=['collector', '-timestamp'], name='collector_c_collect_23e285_idx'),
        ),
        migrations.AddIndex(
            model_name='collectortarget',
            index=models.Index(fields=['collector', 'month', 'year'], name='collector_c_collect_a05654_idx'),
        ),
        migrations.AddIndex(
            model_name='collectortarget',
            index=models.Index(fields=['percentage_achieved'], name='collector_c_percent_03ad27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectortarget',
            unique_together={('collector', 'village', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='vehicleturncount',
            index=models.Index(fields=['vehicle', 'village', 'date'], name='collector_v_vehicle_4c7baa_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleturncount',
            index=models.Index(fields=['monthly_total'], name='collector_v_monthly_ac2314_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleturncount',
            unique_together={('vehicle', 'village', 'date')},
        ),
        migrations.AddIndex(
            model_name='wastecollectionschedule',
            index=models.Index(fields=['collector', 'is_completed'], name='collector_w_collect_d1a885_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollectionschedule',
            index=models.Index(fields=['day_of_week', 'week_number', 'year'], name='collector_w_day_of__3acb39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wastecollectionschedule',
            unique_together={('village', 'day_of_week', 'week_number', 'year')},
        ),
    ]
