# Generated by Django 5.2.7 on 2025-12-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='villages',
        ),
        migrations.RemoveField(
            model_name='historicalcollector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalcollector',
            name='phone',
        ),
    ]
