# Generated by Django 5.2.7 on 2026-01-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_collector_email_remove_collector_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollectionschedule',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.DeleteModel(
            name='CollectorTarget',
        ),
    ]
