# Generated by Django 5.2.7 on 2025-12-21 09:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0004_delete_notification'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at_time'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_8bedf2_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 21, 9, 47, 37, 793827, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('activity', 'Activity Change'), ('message', 'Direct Message'), ('task', 'Task Assignment'), ('leave', 'Leave Update'), ('complaint', 'Complaint Response'), ('loan', 'Loan Status'), ('payment', 'Payment Update'), ('invoice', 'Invoice Update'), ('payroll', 'Payroll Processed'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('chat', 'Chat Message'), ('group', 'Group Activity'), ('admin', 'Admin Action'), ('system', 'System'), ('create', 'New Customer'), ('update', 'Customer Updated'), ('delete', 'Customer Deleted')], default='info', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at_time'], name='notificatio_recipie_b79da8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['unread'], name='notificatio_unread_263214_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
