# Generated by Django 5.2.7 on 2026-01-29 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(default='MFVYOpjwX3zeVHaLuiJp6Z0EXhden3mIhkBH1qrPPCUxpxu9h3MaTQZ8bSkqqJRk', max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Web Push')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('push_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribe_tokens', to='notifications.pushsubscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='notificatio_token_adcb42_idx'), models.Index(fields=['email', 'channel'], name='notificatio_email_d73592_idx'), models.Index(fields=['phone', 'channel'], name='notificatio_phone_b0d5a3_idx')],
                'unique_together': {('email', 'channel'), ('phone', 'channel'), ('user', 'channel')},
            },
        ),
    ]
