# Generated by Django 5.2.7 on 2026-01-30 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_unsubscribetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_push_attempt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent push attempt', null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_push_success',
            field=models.BooleanField(default=False, help_text='Was the most recent push attempt successful?'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_successful_push',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last confirmed successful push', null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='push_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Total failed pushes'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='push_success_count',
            field=models.PositiveIntegerField(default=0, help_text='Total successful pushes'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(default='qbHbCv7aNVi5bJ45r9KAn2eyE0JRsNNC0BBsTPVoiieCpkMf1yOmnbPqCw5ToOlk', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['endpoint'], name='notificatio_endpoin_498a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_e9a308_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['last_successful_push'], name='notificatio_last_su_d35cea_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['last_push_attempt'], name='notificatio_last_pu_d939d5_idx'),
        ),
    ]
