# Generated by Django 5.2.7 on 2026-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_pushsubscription_last_push_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_push_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='push_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(default='aFnSq4WIncRfeuhuNNi74Ga41BgqCF5y8FiUI62N4nO1vc2ywC3ywPUYpT7bZz0i', max_length=64, unique=True),
        ),
    ]
