# Generated by Django 5.2.7 on 2026-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pushsubscription_last_push_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(default='iVQdBoaAy55LL2cBiUjVrdjBBGqSmodVALCpMIQxI9WoOBObxLGQdzF1dauZ1fm2', max_length=64, unique=True),
        ),
    ]
