# Generated by Django 5.2.7 on 2025-12-03 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('crm', 'Customer Relationship Management'), ('finance', 'Financial Management'), ('projects', 'Project Management'), ('hr', 'Human Resources'), ('inventory', 'Inventory Management'), ('procurement', 'Procurement'), ('manufacturing', 'Manufacturing'), ('sales', 'Sales'), ('services', 'Services')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📊', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ERP Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERPDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_dashboard', to=settings.AUTH_USER_MODEL)),
                ('modules', models.ManyToManyField(related_name='dashboards', to='erp.erpmodule')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='erp.erpmodule')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.businessunit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='erp.erpmodule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERPNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('kpi_alert', 'KPI Alert'), ('workflow_step', 'Workflow Step'), ('approval_required', 'Approval Required'), ('data_quality', 'Data Quality'), ('system_alert', 'System Alert')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.businessunit')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.erpmodule')),
                ('recipients', models.ManyToManyField(related_name='erp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='erp_erpnoti_is_read_b8537b_idx'), models.Index(fields=['business_unit', 'module'], name='erp_erpnoti_busines_9bc6ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('revenue', 'Revenue'), ('profit', 'Profit'), ('cost', 'Cost'), ('efficiency', 'Efficiency'), ('growth', 'Growth'), ('customer', 'Customer Satisfaction')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='erp.businessunit')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='erp.erpmodule')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'business_unit', 'period')},
            },
        ),
    ]
