# Generated by Django 5.2.7 on 2025-12-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
