# backend/procurement/ai_agent.py
import google.generativeai as genai
from django.core.mail import EmailMessage
from django.conf import settings
from .models import PurchaseRequisition, PurchaseRequisitionItem, Item
from .ai_assistant import suggest_pr_title_and_items

genai.configure(api_key=settings.GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')  # Fast for agent loop

class ProsperBot:
    def __init__(self):
        self.context = "You are ProsperBot, AI Procurement Director at High Prosper Ltd (solar energy company). You create PRs autonomously."

    def process_incoming_request(self, source: str, content: str, sender: str = ""):
        """
        Called from:
        - Email parser (IMAP)
        - WhatsApp webhook
        - Voice transcription
        - Manual "Ask AI" button
        """
        prompt = f"""
        {self.context}
        
        Incoming request from {source}:
        Sender: {sender}
        Content: "{content}"
        
        Decide:
        1. Is this a valid procurement request? (yes/no)
        2. If yes: Extract department, urgency, items needed
        3. Generate PR title and items using your knowledge
        
        Respond ONLY with JSON:
        {{
            "action": "create_pr" or "ignore" or "clarify",
            "title": "...",
            "department": "...",
            "required_by": "YYYY-MM-DD" or null,
            "notes": "...",
            "items": [
                {{"name": "...", "quantity": 1, "reason": "..." }}
            ],
            "response_message": "Human-readable reply to sender"
        }}
        """

        response = model.generate_content(prompt)
        try:
            import json
            decision = json.loads(response.text)

            if decision["action"] == "create_pr":
                return self.create_pr_from_decision(decision, sender)
            else:
                return {"status": decision["action"], "message": decision["response_message"]}

        except Exception as e:
            return {"error": str(e)}

    def create_pr_from_decision(self, decision: dict, requester_email: str):
        # Find or create requester user
        from users.models import User
        requester, _ = User.objects.get_or_create(email=requester_email, defaults={'username': requester_email.split('@')[0]})

        # Create PR
        pr = PurchaseRequisition.objects.create(
            title=decision["title"],
            department=decision["department"],
            required_by_date=decision.get("required_by"),
            notes=decision["notes"] + f"\n\nAuto-generated by ProsperBot from {requester_email}",
            requester=requester,
            status='draft'
        )

        # Add items
        for it in decision["items"]:
            # Try to match existing item
            item_match = Item.objects.filter(name__icontains=it["name"]).first()
            PurchaseRequisitionItem.objects.create(
                requisition=pr,
                item=item_match,
                description=it["name"],
                quantity=it["quantity"],
                unit_price_estimated=0  # Will be estimated later
            )

        # Notify procurement team
        self.notify_team(pr)

        return {
            "status": "created",
            "pr": pr.pr_number,
            "message": f"PR {pr.pr_number} created autonomously!"
        }

    def notify_team(self, pr):
        send_mail(
            f"New AI-Generated PR: {pr.title}",
            f"ProsperBot created PR {pr.pr_number}\n\nView: https://erp.highprosper.com/admin/procurement/purchaserequisition/{pr.id}/",
            "prosperbot@highprosper.com",
            ["procurement@highprosper.com"]
        )