# Generated by Django 5.2.7 on 2025-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_road', 'On Road'), ('maintenance', 'In Maintenance'), ('passive', 'Passive')], default='active', max_length=20),
        ),
    ]
