# Generated by Django 5.2.7 on 2025-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_brand',
            field=models.CharField(default='MITSUBISHI', max_length=20),
            preserve_default=False,
        ),
    ]
