# Generated by Django 5.2.7 on 2025-12-06 20:32

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_vehicle_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-registration_date'], 'permissions': [('can_view_fleet_dashboard', 'Can view fleet analytics dashboard'), ('can_export_fleet_data', 'Can export fleet reports'), ('can_manage_workshop', 'Can manage workshop records')]},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_service_due',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bdm_kg',
            field=models.DecimalField(decimal_places=2, default=3500, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='BDM (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(default='TEMP-CHASSIS-0000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 6, 20, 29, 36, 185234, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_photo',
            field=models.ImageField(blank=True, null=True, upload_to='damage_inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(default='TEMP-ENGINE-0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='MITHUBISHI', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_reading',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current odometer (km)', max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 20, 32, 3, 242297, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/main/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_road', 'On Road'), ('workshop', 'In Workshop'), ('standby', 'On Standby'), ('maintenance', 'Scheduled Maintenance'), ('retired', 'Retired/Decommissioned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('pickup', 'Pickup'), ('bus', 'Bus'), ('trailer', 'Trailer'), ('special', 'Special Purpose')], max_length=20),
        ),
        migrations.CreateModel(
            name='FuelEfficiencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('km_per_liter', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('cost_per_km', models.DecimalField(decimal_places=3, editable=False, max_digits=8)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_efficiency', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parts_used', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mechanic', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_history', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_type', models.CharField(choices=[('puspakom', 'Puspakom'), ('insurance', 'Insurance'), ('inspection', 'Vehicle Inspection'), ('lpkp', 'LPKP'), ('road_tax', 'Road Tax'), ('traffic_fine', 'Traffic Fine Clearance'), ('burnel_transit', 'Burnel Transit'), ('burnel_interstate', 'Burnel Interstate')], max_length=30)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='compliance/')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['expiry_date'],
                'unique_together': {('vehicle', 'compliance_type')},
            },
        ),
    ]
