# Generated by Django 5.2.7 on 2025-12-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_options_remove_vehicle_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
