# Generated by Django 5.2.7 on 2025-12-21 11:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['name'], 'verbose_name': 'Village', 'verbose_name_plural': 'Villages'},
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='village',
            name='collectors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'collector'}, related_name='assigned_villages', to=settings.AUTH_USER_MODEL, verbose_name='Collectors'),
        ),
        migrations.AlterField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this village currently active?'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='population_estimate',
            field=models.PositiveIntegerField(default=0, help_text='Estimated population of the village', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='village',
            name='collector',
        ),
    ]
