# Generated by Django 5.2.7 on 2025-12-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_village_options_alter_village_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
