# Generated by Django 5.2.7 on 2026-01-01 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['-performance_rank', 'name'], 'verbose_name': 'Village', 'verbose_name_plural': 'Villages'},
        ),
        migrations.AddField(
            model_name='village',
            name='collected_this_month',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='village',
            name='monthly_new_customers_target',
            field=models.PositiveIntegerField(default=0, help_text='Target number of new customers to acquire this month'),
        ),
        migrations.AddField(
            model_name='village',
            name='monthly_revenue_target',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly revenue collection target (RWF)', max_digits=15),
        ),
        migrations.AddField(
            model_name='village',
            name='new_customers_this_month',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='village',
            name='performance_rank',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Village rank this month by target achievement (1 = best)', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='previous_month_collected',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='village',
            name='previous_month_new_customers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='village',
            name='target_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Month this target applies to'),
        ),
        migrations.AddField(
            model_name='village',
            name='target_year',
            field=models.PositiveSmallIntegerField(default=2026, help_text='Year this target applies to'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['target_month', 'target_year'], name='customers_v_target__e0fded_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['performance_rank'], name='customers_v_perform_e181dc_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['monthly_revenue_target'], name='customers_v_monthly_64003d_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['monthly_new_customers_target'], name='customers_v_monthly_3bd328_idx'),
        ),
    ]
