# Generated by Django 5.2.7 on 2026-01-03 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_village_options_village_collected_this_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AddField(
            model_name='sector',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Field Sector Managers responsible for this sector', limit_choices_to={'role': 'manager'}, related_name='managed_sectors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sector',
            name='supervisors',
            field=models.ManyToManyField(blank=True, help_text='Field Site Supervisors operating in this sector', limit_choices_to={'role': 'supervisor'}, related_name='supervised_sectors', to=settings.AUTH_USER_MODEL),
        ),
    ]
