# Generated by Django 5.2.7 on 2026-01-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_sector_options_sector_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requester_nid', models.CharField(blank=True, max_length=30, null=True)),
                ('address_details', models.TextField(help_text='Full address or landmarks')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_date', models.DateField(blank=True, help_text='Preferred service date', null=True)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount quoted by staff', max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount after service', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or completion report')),
                ('satisfaction_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'supervisor', 'collector']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='If requester is an existing customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='customers.village')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='customers_s_status_cac9f1_idx'), models.Index(fields=['payment_status'], name='customers_s_payment_8eb155_idx'), models.Index(fields=['requester_phone'], name='customers_s_request_708080_idx'), models.Index(fields=['village'], name='customers_s_village_29a8cb_idx')],
            },
        ),
    ]
