# Generated by Django 5.2.7 on 2026-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='target_month',
            field=models.PositiveSmallIntegerField(default=2, help_text='Month this target applies to'),
        ),
    ]
