import { Page, View } from "@react-pdf/renderer";

// frontend/components/pdf/ContractDocument.tsx
export default function ContractDocument({ po, company }: { po: any, company: any }) {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>SUPPLY CONTRACT</Text>
                    <Text style={styles.subtitle}>Contract No: {po.po_number}-CON</Text>
                </View>

                <Text style={styles.sectionTitle}>PARTIES</Text>
                <Text>Between: {company.name} ("Buyer")</Text>
                <Text>And: {po.supplier.name} ("Supplier")</Text>

                <Text style={styles.sectionTitle}>SCOPE</Text>
                <Text>Supplier agrees to supply goods as per Purchase Order {po.po_number} dated {po.order_date}.</Text>

                <Text style={styles.sectionTitle}>DELIVERABLES</Text>
                {/* Table of items */}

                <Text style={styles.sectionTitle}>PAYMENT TERMS</Text>
                <Text>{po.payment_terms}</Text>

                <Text style={styles.sectionTitle}>SIGNATURES</Text>
                <View style={{ marginTop: 60 }}>
                    <Text>_________________________        _________________________</Text>
                    <Text>Buyer Representative                    Supplier Representative</Text>
                    <Text>Date: _________________              Date: _________________</Text>
                </View>

                <Text style={styles.footer}>Generated by High Prosper ERP • {new Date().toLocaleDateString()}</Text>
            </Page>
        </Document>
    );
}