# Generated by Django 5.2.7 on 2025-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payoutlog_webhookretry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
