# Generated by Django 5.2.7 on 2026-01-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_servicerequest'),
        ('payments', '0003_fix_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.servicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
    ]
