# Generated by Django 5.2.7 on 2025-12-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_ledgerentry_serviceorder_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='customers.sector'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_account',
            field=models.CharField(default='DEFAULT-ACCOUNT', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='cell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='customers.cell'),
            preserve_default=False,
        ),
    ]
