# Generated by Django 5.2.7 on 2025-12-05 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('chat', 'Chat Message'), ('group', 'Group Activity'), ('admin', 'Admin Action'), ('system', 'System'), ('leave', 'Leave Request'), ('payroll', 'Payroll'), ('task', 'Task')], default='info', max_length=20)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_time'],
                'indexes': [models.Index(fields=['user', '-created_at_time'], name='users_notif_user_id_45e161_idx'), models.Index(fields=['is_read'], name='users_notif_is_read_316047_idx')],
            },
        ),
    ]
