# Generated by Django 5.2.7 on 2025-12-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_global_admin',
            field=models.BooleanField(default=False),
        ),
    ]
