# Generated by Django 5.2.7 on 2025-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_browser',
            field=models.BooleanField(default=True, help_text='Receive browser push notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_customer_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_leave',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_realtime',
            field=models.BooleanField(default=True, help_text='Receive real-time WebSocket notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_sms',
            field=models.BooleanField(default=True, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_sound',
            field=models.BooleanField(default=True, help_text='Play notification sounds'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_task',
            field=models.BooleanField(default=True),
        ),
    ]
