# Generated by Django 5.2.7 on 2025-12-28 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_options_customuser_notify_browser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('results_count', models.PositiveIntegerField()),
                ('has_results', models.BooleanField()),
                ('clicked_result', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query'], name='users_searc_query_2f07a5_idx'), models.Index(fields=['timestamp'], name='users_searc_timesta_9c898a_idx'), models.Index(fields=['user', 'timestamp'], name='users_searc_user_id_cbd47d_idx')],
            },
        ),
    ]
