# Generated by Django 5.2.7 on 2026-01-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_branch_alter_company_options_company_address_and_more'),
        ('users', '0010_customuser_bio_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.branch', verbose_name='Branch'),
        ),
    ]
