# Generated by Django 5.2.7 on 2026-01-20 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0013_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blocked User', 'verbose_name_plural': 'Blocked Users'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='object_id',
            new_name='target_object_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='content_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/moderator who performed the block (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the block expires (optional)', null=True),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-unblock support'),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated'), ('posted', 'Posted Content'), ('commented', 'Commented'), ('shared', 'Shared Content'), ('reacted_like', 'Liked'), ('reacted_love', 'Loved'), ('reacted_other', 'Other Reaction'), ('friended', 'Added Friend/Followed'), ('unfriended', 'Removed Friend/Unfollowed'), ('blocked_user', 'Blocked User'), ('unblocked_user', 'Unblocked User'), ('joined_group', 'Joined Group'), ('left_group', 'Left Group'), ('other', 'Other Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('admin', 'Admin'), ('hr', 'HR'), ('accounting', 'Accounting'), ('manager', 'Field Sector Manager'), ('supervisor', 'Field Site Supervisor'), ('collector', 'Collector'), ('staff', 'Staff'), ('driver', 'Driver'), ('manpower', 'Manpower'), ('customer', 'Customer'), ('user', 'Regular User')], default='customer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['action_type', '-created_at'], name='users_activ_action__13e7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='users_activ_created_4767f2_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocker', 'blocked'], name='users_block_blocker_8b2e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['is_active', 'expires_at'], name='users_block_is_acti_2a74bd_idx'),
        ),
    ]
