# Generated by Django 5.2.7 on 2026-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_activity_options_alter_blockeduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
